### ISSUE TITLE
Would love to help build out the streamlit app

### ISSUE THREAD

**Issue by digitalghost-dev** [data-engineering-community/data-engineering-salaries#2]
Hey, again.  I’ve helped in the past with the data engineering wiki. I just noticed this repo and I have been building a Streamlit app myself lately: [repo](https://github.com/digitalghost-dev/premier-league), so I am familiar with working with Streamlit. Not sure what the vision is on this but would love to help out!

**Comment by JPHaus** [comment]
Hey @digitalghost-dev! We are tracking the project using the [GitHub project](https://github.com/data-engineering-community/data-engineering-salaries/projects) in the repo. Right now we are just working on getting V1 out so folks can use it but after that it's really open to the community's ideas!

**Comment by JPHaus** [comment]
Also, when you accept the invite we will add you to the GitHub project board. We want to use this to track who is working on what so we don't overlap on the work.

**Comment by Mega-Barrel** [comment]
Hi @JPHaus, I am also interested in collaborating on this project, and I have implemented a fix for the #4 feature.
