### ISSUE TITLE
Enhancement: Auto-refresh with Docker & Streamlit

### ISSUE THREAD

**Issue by mrjaketomlinson** [data-engineering-community/data-engineering-salaries#4]
Enhancement: Update the docker (compose) build so that the streamlit app will automatically refresh when changes are made to the app code.

It'd be nice to add this feature so that you don't have to rebuild the docker image when you want to see your changes if you want to develop using Docker. It's probably simple enough with docker-compose, but I'm adding it here if anyone wants to pick it up.

**Comment by JPHaus** [comment]
You shouldn't have to rebuild the docker image - you can just stop and start the container. But I agree this would be nice. I'll let someone else get the experience.

**Comment by Mega-Barrel** [comment]
Hi @mrjaketomlinson, I've implemented a working solution for this feature using _docker-compose_, how do I go about creating a PR for this feature?

Thanks,
Saurabh
