### ISSUE TITLE
Would love to collaborate on the DE Salaries project

### ISSUE THREAD

**Issue by Mega-Barrel** [data-engineering-community/data-engineering-salaries#8]
Hi @JPHaus, I am interested in collaborating on this project, can you please invite/add me to the GitHub project board? I have developed various streamlit apps. Example repo: [SQL Question Tracker](https://sql-question-dashboard.streamlit.app/)

**Comment by JPHaus** [comment]
Just sent you an invite to the repo and after you accept that invite I can add you to the project.
